version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    # Additional configuration...
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # Additional configuration... 